# This file was generated by project setup for project Magistrat_28_54.
# As you work on the project, you should add commands to this file so that
# it contains the commands needed to rebuild the whole project from scratch.
# Typically, those will be source() or rmarkdown::render() calls, like below.

source("001_retrieve-data.R", local = TRUE)
source('002_read-data-teachers.R', local = TRUE)
source('002_read-data-marks.R', local = TRUE)
source('003_check-and-process-data-teachers.R', local = TRUE)
source('003_check-and-process-data-marks.R', local = TRUE)
rmarkdown::render('01_quantitative_report_call_28.Rmd', output_dir = 'reports-output')



